ASP/ASP/Models/Forum/CreateSectionModel.cs
namespace ASP.Models.Forum;

public class CreateSectionModel
{
    public string? Title { get; set; } = "";
    public string? Description { get; set; } = "";
}

ASP/ASP/Models/Forum/CreateThemeModel.cs
using ASP.Data.Entity;

namespace ASP.Models.Forum;

public class CreateThemeModel
{
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
    public Guid SectionId { get; set; }
}

ASP/ASP/Models/Forum/ForumIndexModel.cs
using ASP.Data.Entity;

namespace ASP.Models.Forum;

public class ForumIndexModel
{
    public bool UserCanCreate { get; set; }
    public List<ForumSectionModel> Sections { get; set; } = null!;
    public string CreateMessage { get; set; } = "";
    public bool IsMessagePositive { get; set; }
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumPostFormModel.cs
namespace ASP.Models.Forum;

public class ForumPostFormModel
{
    public string Content { get; set; } = "";
    public string TopicId { get; set; } = "";
    public string ReplyId { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumPostViewModel.cs
namespace ASP.Models.Forum;

public class ForumPostViewModel
{
    public string Content { get; set; } = "";
    public string CreatedDt { get; set; }
    public string AuthorAvatar { get; set; } = "";
    public string AuthorName { get; set; } = "";
    public string ReplyPreview { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumSectionModel.cs
namespace ASP.Models.Forum;

public class ForumSectionModel
{
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
    public string Logo { get; set; } = "";
    public string CreatedDtString { get; set; } = "";
    public string Author { get; set; } = "";
    public string Avatar { get; set; } = "";
    public string UrlId { get; set; } = "";
    
    public int LikeCount { get; set; } = 0;
    public int DislikeCount { get; set; } = 0;
}

ASP/ASP/Models/Forum/ForumSectionsModel.cs
namespace ASP.Models.Forum;

public class ForumSectionsModel
{
    public bool UserCanCreate { get; set; }
    public List<ForumThemeModel> Themes { get; set; } = null!;  

    public string CreateMessage { get; set; } = "";
    public bool IsMessagePositive { get; set; }
    public CreateThemeModel FormModel { get; set; } = null!;
}

ASP/ASP/Models/Forum/ForumThemeFormModel.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.Models.Forum
{
    public class ForumThemeFormModel
    {
        public String Title { get; set; } = null!;

        public String Description { get; set; } = null!;
        
        public string LogoId { get; set; } = null!;

        public String SectionId { get; set; } = null!;
    }
}

ASP/ASP/Models/Forum/ForumThemeModel.cs
namespace ASP.Models.Forum;

public class ForumThemeModel
{
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
    public string CreatedDtString { get; set; } = "";
    public string Author { get; set; } = "";
    public string Avatar { get; set; } = "";
    public string UrlId { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumThemesPageModel.cs
namespace ASP.Models.Forum;

public class ForumThemesPageModel
{
    public bool UserCanCreate { get; set; }
    public List<ForumTopicViewModel> Topics { get; set; } = null!;
    public string Title { get; set; } = "";
    public string ThemeId { get; set; } = "";
    public string CreateMessage { get; set; } = "";
    public bool IsMessagePositive { get; set; }
    public ForumTopicFormModel FormModel { get; set; } = null!;
    public string LogoId { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumTopicFormModel.cs
namespace ASP.Models.Forum;

public class ForumTopicFormModel
{
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
    public string ThemeId { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumTopicViewModel.cs
namespace ASP.Models.Forum;

public class ForumTopicViewModel
{
    public string Title { get; set; } = "";
    public string Description { get; set; } = "";
    public string CreatedDtString { get; set; } = "";
    public string Author { get; set; } = "";
    public string Avatar { get; set; } = "";
    public string UrlId { get; set; } = "";
}

ASP/ASP/Models/Forum/ForumTopicsPageModel.cs
namespace ASP.Models.Forum;

public class ForumTopicsPageModel
{
    public bool UserCanCreate { get; set; }
    public List<ForumPostViewModel> Posts { get; set; } = null!;
    public string Title { get; set; } = "";
    public string TopicId { get; set; } = "";
    public string Description { get; set; } = "";
    public string CreateMessage { get; set; } = "";
    public bool IsMessagePositive { get; set; }
    public ForumTopicFormModel FormModel { get; set; } = null!;
}

ASP/ASP/Controllers/ForumController.cs
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using ASP.Data;
using ASP.Data.Entity;
using ASP.Models.Forum;
using ASP.Services.Display;
using ASP.Services.Validation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASP.Controllers;

public class ForumController : Controller
{
    private readonly DataContext _dataContext;
    private readonly IValidation _validation;
    private readonly IDisplayService _displayService;

    public ForumController(
        DataContext dataContext,
        IValidation validation,
        IDisplayService displayService
    )
    {
        _dataContext = dataContext;
        _validation = validation;
        _displayService = displayService;
    }

    private int _counter = -1;

    private int Counter
    {
        get
        {
            _counter++;
            return _counter;
        }
    }

    public IActionResult Index()
    {
        ForumIndexModel model = new()
        {
            UserCanCreate = HttpContext.User.Identity?.IsAuthenticated == true,
            Sections = _dataContext.Sections
                .Include(s => s.Author)
                .Include(s => s.RatesList)
                .OrderBy(s => s.CreatedDt)
                .AsEnumerable()
                .Select(s =>
                {
                    return new ForumSectionModel()
                    {
                        Description = s.Description,
                        Title = s.Title,
                        Logo = $"section{Counter}.png",
                        CreatedDtString = s.CreatedDt.ToString("dd.MM.yyyy HH:mm"),
                        Author = s.Author.Username,
                        Avatar = s.Author.AvatarFileName,
                        UrlId = s.AuthorId.ToString(),
                        LikeCount = s.RatesList.Count(r => r.Rating > 0),
                        DislikeCount = s.RatesList.Count(r => r.Rating < 0),
                    };
                }).ToList(),
        };
        model.IsMessagePositive = HttpContext.Session.GetInt32("IsMessagePositive") != 0;
        model.Title = HttpContext.Session.GetString("SectionTitle") ?? String.Empty;
        model.Description = HttpContext.Session.GetString("SectionDescription") ?? String.Empty;
        model.CreateMessage = HttpContext.Session.GetString("CreateMessage") ?? String.Empty;
        model.UserCanCreate = HttpContext.User.Identity?.IsAuthenticated == true;
        if (HttpContext.Session.GetString("CreateMessage") is string message)
        {
            model.CreateMessage = message;
            HttpContext.Session.Remove("CreateMessage");
        }

        return View(model);
    }

    public ViewResult Sections([FromRoute] string id)
    {
        ViewData["id"] = id;
        try
        {
            var model = new ForumSectionsModel()
            {
                UserCanCreate = HttpContext.User.Identity.IsAuthenticated == true,
                Themes = _dataContext.Themes.Include(t => t.Author)
                    .Where(t => t.SectionId == Guid.Parse(id))
                    .OrderBy(t => t.CreatedDt).AsEnumerable().Select(t =>
                    {
                        return new ForumThemeModel()
                        {
                            Description = t.Description,
                            Title = t.Title,
                            LogoId = t.LogoId ?? "0",
                            DaysSinceRegister =
                                _displayService.NumberOfDaysBetweenDates(DateTime.Now, t.Author.RegisterDate),
                            AuthorRegisterDateString = t.Author.RegisterDate.ToString("dd.MM.yyyy HH:mm"),
                            CreatedDtString = t.CreatedDt.ToString("dd.MM.yyyy HH:mm"),
                            UrlId = t.Id.ToString(),
                            Author = t.Author.Username,
                            Avatar = t.Author.AvatarFileName,
                        };
                    }).ToList(),
            };

            if (HttpContext.Session.GetString("CreateMessage") is String message)
            {
                model.CreateMessage = message;
                model.IsMessagePositive =
                    HttpContext.Session.GetInt32("IsMessagePositive") != 0;


                if (model.IsMessagePositive == false)
                {
                    model.FormModel = new()
                    {
                        Title = HttpContext.Session.GetString("SectionTitle")!,
                        Description = HttpContext.Session.GetString("SectionDescription")!
                    };
                    HttpContext.Session.Remove("SectionTitle");
                    HttpContext.Session.Remove("SectionDescription");
                }


                HttpContext.Session.Remove("CreateMessage");
                HttpContext.Session.Remove("IsMessagePositive");
            }

            return View(model);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }

        return View();
    }

    [HttpPost]
    public RedirectToActionResult CreateSection(CreateSectionModel model)
    {
        try
        {
            Console.WriteLine(model.Description);
            Console.WriteLine(model.Title);
            if (string.IsNullOrEmpty(model.Description))
            {
                HttpContext.Session.SetString("CreateMessage", "Description is empty");
                HttpContext.Session.SetInt32("IsMessagePositive", 0);
                HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
                HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);
            }

            else if (string.IsNullOrEmpty(model.Title))
            {
                HttpContext.Session.SetString("CreateMessage", "Title is empty");
                HttpContext.Session.SetInt32("IsMessagePositive", 0);
                HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
                HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);
            }
            else
            {
                _dataContext.Sections.Add(new()
                {
                    Title = model.Title,
                    Description = model.Description,
                    Id = Guid.NewGuid(),
                    CreatedDt = DateTime.Now,
                    AuthorId = Guid.Parse(HttpContext.User.Claims.First(c => c.Type == ClaimTypes.Sid)?.Value),
                });
                _dataContext.SaveChanges();
                HttpContext.Session.SetString("CreateMessage", "Section created");
                HttpContext.Session.SetInt32("IsMessagePositive", 1);
                HttpContext.Session.SetString("SectionTitle", "");
                HttpContext.Session.SetString("SectionDescription", "");
            }
        }
        catch
        {
            HttpContext.Session.SetString("CreateMessage", "Error creating section");
            HttpContext.Session.SetInt32("IsMessagePositive", 0);
            HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
            HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public RedirectToActionResult CreateTheme(ForumThemeFormModel model)
    {
        if (string.IsNullOrEmpty(model.Description))
        {
            HttpContext.Session.SetString("CreateMessage", "Description is empty");
            HttpContext.Session.SetInt32("IsMessagePositive", 0);
            HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
            HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);
        }
        else if (string.IsNullOrEmpty(model.Title))
        {
            HttpContext.Session.SetString("CreateMessage", "Title is empty");
            HttpContext.Session.SetInt32("IsMessagePositive", 0);
            HttpContext.Session.SetString("SectionTitle", model.Title ?? String.Empty);
            HttpContext.Session.SetString("SectionDescription", model.Description ?? String.Empty);
        }
        else
        {
            try
            {
                _dataContext.Themes.Add(new()
                {
                    Title = model.Title,
                    Description = model.Description,
                    Id = Guid.NewGuid(),
                    LogoId = model.LogoId ?? "0",
                    CreatedDt = DateTime.Now,
                    AuthorId = Guid.Parse(HttpContext.User.Claims.First(c => c.Type == ClaimTypes.Sid)?.Value),
                    SectionId = Guid.Parse(model.SectionId),
                });
                _dataContext.SaveChanges();
                HttpContext.Session.SetString("CreateMessage", "Theme created");
                HttpContext.Session.SetInt32("IsMessagePositive", 1);
                HttpContext.Session.SetString("SectionTitle", "");
                HttpContext.Session.SetString("SectionDescription", "");
            }
            catch
            {
            }
        }

        return RedirectToAction(nameof(Sections), new { id = model.SectionId.ToString() });
    }

    public IActionResult Themes([FromRoute] string id)
    {
        Theme? theme = null;
        try
        {
            theme = _dataContext.Themes.Where(t => t.Id == Guid.Parse(id)).First();
        }
        catch
        {
        }

        if (theme == null)
        {
            return NotFound();
        }

        ViewData["id"] = id;

        ForumThemesPageModel model = new()
        {
            UserCanCreate = HttpContext.User.Identity.IsAuthenticated == true,
            Title = theme.Title,
            ThemeId = id,
            CreateMessage = HttpContext.Session.GetString("CreateMessage") ?? String.Empty,
            FormModel = new ForumTopicFormModel()
            {

ASP/ASP/Views/Forum/Index.cshtml
@model ASP.Models.Forum.ForumIndexModel
<h1>Forum</h1>
<div class="flex ">

    @if (Model.Sections.Count > 0)
    {
        foreach (var section in Model.Sections)
        {
            @Html.DisplayFor(m => section, "Section")
        }
    }

</div>

@if (Model.UserCanCreate)
{
    <div class="row">
        <div class="col col-6">
            <h5 class="modal-title" id="authModalLabel">Створити новий розділ</h5>
            <form asp-controller="Forum" asp-action="CreateSection" method="post">
                <div class="form-group">
                    @if (Model.IsMessagePositive)
                    {
                        <div class="alert alert-success" role="alert">
                            @Model.CreateMessage
                        </div>
                    }
                    else if (Model.IsMessagePositive)
                    {
                        <div class="alert alert-danger" role="alert">
                            @Model.CreateMessage
                        </div>
                    }
                    <label for="section-title">Назва</label>
                    <input type="text" class="form-control"
                           id="Title" name="Title"
                           value="@Model.Title"
                           placeholder="Назва розділу"/>
                </div>
                <div class="form-group">
                    <label for="section-description" class="form-label">Опис</label>
                    <textarea class="form-control" id="section-description" rows="3"
                
                name="Description" placeholder="Опис нового розділу">
                @Model.Description
                </textarea>
                </div>
                <button type="submit" class="btn btn-primary">Створити</button>
            </form>
        </div>
    </div>
}

<script>
    document.addEventListener("DOMContentLoaded",()=>{
        console.log("loaded")
        const userSid = document.querySelector("[data-user-sid]")
        for (let elem of document.querySelectorAll("[data-rate]")){
            elem.addEventListener("click",()=>{
                const rate = elem.getAttribute("data-rate")
                const val = elem.getAttribute("data-rate-value")
                console.log(rate)
                console.log(val)
                const data={
                    "ItemId":rate,
                    "UserId":userSid,
                    "Value":val    
                }
                
                fetch("/api/rates/rate",
                {
                    method:"POST",
                    headers:{
                        "Content-Type":"application/json"
                    },
                    body:JSON.stringify(data)
                }).then(res=>res.json())
                .then(data=>console.log(data))
                console.log(data)
            })
        }
    })
</script>

ASP/ASP/Views/Forum/Sections.cshtml
@model ASP.Models.Forum.ForumSectionsModel
<a>@ViewData["Id"]</a>


@foreach(var Theme in Model.Themes)
{
    @Html.DisplayFor(m => Theme, "ThemeTemplate")
}
@if (Model.UserCanCreate)
{
    <div class="row">
        <div class="col col-6">
            
            
            
            <h5 class="modal-title" id="authModalLabel">Створити новий розділ</h5>
            <form asp-controller="Forum" asp-action="CreateTheme" method="post">
                <div class="form-group">
                    @if (Model.IsMessagePositive)
                    {
                        <div class="alert alert-success" role="alert">
                            @Model.CreateMessage
                        </div>
                    }
                    else if (Model.IsMessagePositive)
                    {
                        <div class="alert alert-danger" role="alert">
                            @Model.CreateMessage
                        </div>
                    }
                    <label for="section-title">Назва</label>
                    <input type="text" class="form-control"
                           id="Title" name="Title"
                           value="@Model.FormModel?.Title"
                           placeholder="Назва розділу"/>
                </div>
                <div class="form-group">
                    <label for="section-description" class="form-label">Опис</label>
                    <textarea class="form-control" id="section-description" rows="3"
                
                name="Description" placeholder="Опис нового розділу">
                @Model.FormModel?.Description
                </textarea>
                </div>
                <input type="hidden" name="SectionId" value="@ViewData["id"]"/>
                <button type="submit" class="btn btn-primary">Створити</button>
            </form>
        </div>
    </div>
}

ASP/ASP/Views/Forum/Themes.cshtml
@model ASP.Models.Forum.ForumThemesPageModel

@{
    ViewData["Title"] = "Themes";
}
<p>@ViewData["id"]</p>
<h1>@Model.Title</h1>

@foreach (var topic in Model.Topics)
{
    @Html.DisplayFor(m => topic, "TopicTemplate")
}

@if (Model.UserCanCreate)
{
    <form asp-controller="Forum" asp-action="CreateTopic" method="post">
        <div class="form-group">
            @if (Model.IsMessagePositive)
            {
                <div class="alert alert-success" role="alert">
                    @Model.CreateMessage
                </div>
            }
            else if (Model.IsMessagePositive)
            {
                <div class="alert alert-danger" role="alert">
                    @Model.CreateMessage
                </div>
            }
            <label for="Title">Назва</label>
            <input type="text" class="form-control"
                   id="Title" name="Title"
                   value="@Model.Title"
                   placeholder="Назва розділу"/>
            <label for="LogoId">Logo Id</label>
            <select id="LogoId" name="LogoId">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
            </select>
        </div>
        <div class="form-group">
            <label for="Description" class="form-label">Опис</label>
            <textarea class="form-control" id="Description" rows="3"
                
                name="Description" placeholder="Опис нового розділу">
                @Model.FormModel?.Description
                </textarea>
        </div>
        <input type="hidden" name="ThemeId" value="@ViewData["id"]"/>
        <button type="submit" class="btn btn-primary">Створити</button>
    </form>
}

ASP/ASP/Views/Forum/Topics.cshtml
@model ASP.Models.Forum.ForumTopicsPageModel

@{
    ViewData["Title"] = "Topics";
}

<div>@Model.TopicId</div>

<div class="card">
    <div class="card-body">
        <h1>@Model.Title</h1>
        <p>@Model.Description</p>
    </div>
</div>

@foreach (var post in Model.Posts)
{
    @Html.DisplayFor(m => post, "PostTemplate")
}



@if (Model.UserCanCreate)
{
    <form asp-controller="Forum" asp-action="CreatePost" method="post">
        <div class="form-group">
            <label for="Description" class="form-label">Вiдповiдь</label>
            <textarea class="form-control" id="topic-description" rows="3"
                
                name="Description" placeholder="Напишiть вiдповiдь">
                @Model.FormModel?.Description
                </textarea>
        </div>
        <input type="hidden" name="TopicId" value="@Model.TopicId"/>
        <input type="hidden" name="ValueId" value=""/>
        <button type="submit" class="btn btn-primary">Опублiкувати</button>
    </form>
}